pipeline {
    agent any

    stages {

        stage('Verify Folder') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'ls'
                    } else {
                        bat 'dir'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Varad_Mandhare_ADT23SOCB1574') {
                    script {
                        if (isUnix()) {
                            sh 'docker build -t learnscape .'
                        } else {
                            bat 'docker build -t learnscape .'
                        }
                    }
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    if (isUnix()) {
                        sh '''
                        docker stop learnscape_app || true
                        docker rm learnscape_app || true
                        docker run -d -p 3000:80 --name learnscape_app learnscape
                        '''
                    } else {
                        bat '''
                        docker stop learnscape_app || exit 0
                        docker rm learnscape_app || exit 0
                        docker run -d -p 3000:80 --name learnscape_app learnscape
                        '''
                    }
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'docker ps'
                    } else {
                        bat 'docker ps'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'SUCCESS ✅'
        }
        failure {
            echo 'FAILED ❌'
        }
    }
}
